---
title: "DAta analysis of Peel Test"
description: |
  A new article created using the Distill format.
author:
  - name: Catalina
    url: https://example.com/norajones
    affiliation: ERPI
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
#output: distill::distill_article
output: pdf_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library (DescTools)
```


# Loading the data

```{r, include=FALSE}

# Reading all sheet from excel
path <- c('Data/T test -20210510_Hakim2.xls')
Data <- lapply(excel_sheets(path), read_excel, path = path)

# Changing the names of the document
nombres <- Data[[2]]$...1 %>% na.omit()
nombres <- c("Inicial", "Parametros", nombres[11:26], "Parametros 2", "Resultado PLA - TPU", "Resultados PLA COPE")

# Colocando los nombres
Data <- Data %>% set_names(nombres[1:21]) 

# use magrittr function to filter the list
Data <- Data %>% magrittr::extract(nombres[3:18]) # 

# PUtting the rigth names columns to each test
Data <- Data %>% map(~ .x %>% set_names("Course", "Force", 
                                        "Allongement","Allongement nominal", "Temps", "Cycle"))

# Deleting the first Four rowss  at each dataframe
Data <- Data %>% map(~ .x %>% slice(3:n()))

# Changing data as numeric to do stats
Data <- Data %>% map(~ .x %>% modify_if(is.character, as.double))
  
# Creating the Dataframe of Analisys
Data <- Data %>%  enframe("Sample", "Datos")


# Calculating the Median value for each sample
Data <- Data %>% mutate(Force_Adhesion = map_dbl(Datos,  function(df) median(df$Force)))


# Calculating the Max value of force
Data <- Data %>% mutate(Max_force = map_dbl(Datos, function(df) max(df$Force)))


## Function to identify Young Modulus

### Test
#df <- Data$Datos[[1]]

Young <- function(df) {
  
  # Max value for each database
  F_max <- max(df$Force)
  
  # Filtering the Dataframe between Row 1 to row that the value is the max
  
  df <- df %>% filter(between(row_number(), 1, which(df$Force == F_max)))
  
  # Doing the linear model
   model= lm(Force ~ Course, data = df)
   E= coefficients(model)[[2]]
  return(E)
}
  
# Calculating the young Modulus
Data <- Data %>% mutate(Young = map_dbl(Datos, Young))


## Calculating the AUC 

Area_curva <- function(df) {
  
  #df <- Data$Datos[[1]] #Test
  # Filtering the data
  df <- df %>% filter(Course < 40)

  # Calculating the area
  area <-  AUC(df$Course, df$Force, from =0, to= 40, method = "step")
  
  return(area)
}
  
# AUC
Data <- Data %>% mutate(Bonding_energie = map_dbl(Datos, Area_curva))


# Calculating the young Modulus
#Data <- Data %>% separate(col="Sample", sep = "_", into = c("1", "2", "3", "4"))


# test
Data$Material <- c(rep(c("PLA-TPU", "PLA-COPE"), each = 8) )
Data$Echantillon <- c(rep(LETTERS[1], each = 2) ,
                 "C",
                 rep(LETTERS[2], each = 2),
                 "C",
                 rep(LETTERS[4], each = 2),
                 rep(LETTERS[1:4], each = 2) )
  
  

#Valores_medios <- Data %>% group_by(test) %>% summarise(F_mean=mean(Max_force),
#                                                        Young_mean=mean(Young))


```


# TAble summery
```{r}
library(rmarkdown)
paged_table(Data %>% select(-Datos))
```


# Graphs

```{r}
Data %>% 
  ggplot(aes(x= Echantillon, y =Young)) +
  geom_boxplot() +
  facet_grid(~Material)+
  coord_cartesian(ylim = c(0, 3))+
  labs(y="Young Modulus (kN)", x="Echantillons") 
  
```


# Line graph PLA- TPU 
```{r}

Data %>% 
  ggplot ()+
    geom_line(data = Data[[2]][[1]], mapping = aes (x= Course, y=Force,  color = "red"))  +
   geom_line(data = Data[[2]][[2]], mapping = aes (x= Course, y=Force, color = "black")) +
  geom_line(data = Data[[2]][[3]], mapping = aes (x= Course, y=Force, color = "21.78")) +
  geom_line(data = Data[[2]][[4]], mapping = aes (x= Course, y=Force, color = "21.83")) +
 geom_line(data = Data[[2]][[5]], mapping = aes (x= Course, y=Force, color = "21.83")) +
geom_line(data = Data[[2]][[6]], mapping = aes (x= Course, y=Force,color = "21.78")) +
geom_line(data = Data[[2]][[7]], mapping = aes (x= Course, y=Force, color = "21.73")) +
  geom_line(data = Data[[2]][[8]], mapping = aes (x= Course, y=Force, color = "21.73")) +
  labs ( title = "PLA-TPU", y= "Load (N)", x="Extension (mm)")
  
  
```
